site_name: "Jamkit 개발자 가이드"
theme:
  name: material
  language: ko
  logo: assets/logo.png
  favicon: assets/favicon-32x32.png
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
plugins:
  - search
extra:
  disqus: wsl-firststep
markdown_extensions:
  - meta
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - 개요:
    - index.md
    - overview/about.md
    - overview/architecture.md
  - 시작하기:
    - getting-started/requirements.md
    - getting-started/install-windows.md
    - getting-started/install-macos.md
    - getting-started/configure-ide.md
    - getting-started/first-run.md
  - 기본:
    - jamkit/catalog-configuration.md
    - jamkit/sbml-sbss.md
    - jamkit/smart-book-style-sheet.md
    - jamkit/javascript.md
  - 튜토리얼:
    - tutorial/index.md
    - tutorial/layout-day1/README.md
    - tutorial/layout-day2/README.md
    - tutorial/showcase-object-day1.md
    - tutorial/showcase-object-day2/README.md
    - tutorial/day-3.md
    - tutorial/panes.md
    - tutorial/action.md
    - tutorial/form-submit.md
    - tutorial/navigation-script.md
    - tutorial/js.md
    - tutorial/10.md
  - 질문과 답변:
    - support/troubleshoot.md
  - 참조 문서:
    - reference/jamkit-cli.md
    - reference/install-android-oem.md
    - reference/basic-style.md
    - reference/basic-object.md
    - reference/container-object.md
  - GitHub: https://github.com/bookjam/jamkit
